import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useContractKit } from "@celo-tools/use-contractkit";

export default function Home() {
  const { address, openModal } = useContractKit();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {address ? (
          <div>Connected to {address}</div>
        ) : (
          <button onClick={openModal}>Connect wallet</button>
        )}
      </main>
      >
    </div>
  );
}
